# Generated by Django 3.2.3 on 2021-06-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
